// const chalk = require('chalk');
const {execSync} = require('child_process');
// const {runCommand, biLogger} = require('@wix/shono-internal-utils');
// const {shonoCreateCommand, shonoCreateAttempt} = require('@wix/bi-logger-shono/v2');

module.exports = {
  templatesOptions: {
    'wix-one-app-module': {
      functions: {
        files: () => {
          return JSON.stringify([
            'production-e2e',
            'module.*.json',
            'fedops.json',
            '!*/**/*.spec.*',
            'strings',
            'src',
          ]);
        },
      },
      hooks: {
        preTemplateGeneration: (context) => {
          const {moduleName} = context.parametersValues;

          // biLogger.report(shonoCreateAttempt({
          //   moduleName,
          // }));
        },
        postTemplateGeneration: (context) => {
          const {moduleName, slackChannel, ownerEmail} = context.parametersValues;
          const {targetRoot} = context;
          const gitignoreContents = [
            'node_modules',
            'engine_autogenerated',
            'build',
            'coverage',
            '.idea',
            '.vscode',
            'package-lock.json',
            'module.*.json',
            'metro.config.js',
            'babel.config.js',
          ];

          execSync(`echo "${gitignoreContents.join('\n')}" > ${targetRoot}/wix-one-app-${moduleName}/.gitignore`);
          execSync(`git init ${targetRoot}/wix-one-app-${moduleName}`);

          // biLogger.report(shonoCreateCommand({
          //   moduleName,
          //   ownerEmail,
          //   slackChannel,
          // }));

    //       return console.log(`
  
    //   ${chalk.cyan.bold('Run Instructions:')}
    //     ${chalk.yellow(`cd ${moduleName} && npm install && npx shono start -ur`)}
    // `);
        },
      },
      parametersOptions: {
        moduleName: {
          question: 'Please provide a module name (your module will be called wix-one-app-{moduleName}):',
          validation: (answer) => answer.includes('wix-one-app') ? 'Please provide a module name without the prefix wix-one-app, we will prepend it for you' : true,
        },
        moduleOwner: {
          question: 'Please enter the name of the project owner:',
          validation: (answer) => answer.length > 0 ? true : 'Must not be empty!',
        },
        ownerEmail: {
          question: 'Please enter the email of the project owner:',
          validation: (answer) => answer.endsWith('@wix.com') ? true : 'Please provide a valid wix email!',
        },
        slackChannel: {
          question: 'Please provide a slack channel for notifications:',
          validation: (answer) => answer.length > 0 ? true : 'Must not be empty!',
        },
      },
    },
  },
};
